# Generated by Django 5.1.6 on 2025-03-01 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="apartament_number",
            new_name="apartment_number",
        ),
    ]
