# Generated by Django 5.1.6 on 2025-03-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_itemimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clothingitem",
            name="discount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
